on:
  push: null
  workflow_dispatch:
    branches:
      - main
jobs:
  run_tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: temurin
          cache: maven
      - name: Run all tests in project
        run: |
          mvn compile && mvn test
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: test-coverage-report
          path: target/site/jacoco/
          retention-days: 7
  update_coverage_report:
    needs: run_tests
    permissions:
      contents: read
      pages: write
      id-token: write
    uses: ./.github/workflows/test_coverage_report.yaml